Vehicle: BASE3
Designer: Wildman
Body: Panzy
Engine: Small Electric
W#0: T1 Pulse Laser
W#1: T2 Pulse Laser
W#2: T2 Pulse Laser
W#3: T3 Pulse Laser
W#4: T3 Pulse Laser
W#5: T4 Pulse Laser
Armor Type: New Tungsten
Front: 35
Back: 35
Left: 35
Right: 35
Top: 5
Bottom: 0
Special: Console
Special: Mapper
Special: Repair
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Tac Link
Special: Camo
Heat sinks: 40
Suspension: Light
Treads: Spiked
Bumpers: None
