Vehicle: BASE2
Designer: Wildman
Body: Panzy
Engine: Small Electric
W#0: T1 Tactical Nuke
W#1: T2 Pulse Laser
W#2: T2 Pulse Laser
W#3: T3 Pulse Laser
W#4: T3 Pulse Laser
W#5: T4 Pulse Laser
Armor Type: Crumple
Front: 550
Back: 500
Left: 504
Right: 550
Top: 550
Bottom: 499
Special: Console
Special: Mapper
Special: Repair
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Camo
Heat sinks: 40
Suspension: Light
Treads: Spiked
Bumpers: None
