Vehicle: BASE4
Designer: Wildman
Body: Panzy
Engine: Small Electric
W#0: T1 Blast Cannon
W#1: T2 Blast Cannon
W#2: T2 Blast Cannon
W#3: T3 Blast Cannon
W#4: T3 Blast Cannon
W#5: T4 Blast Cannon
Armor Type: Carapice
Front: 110
Back: 80
Left: 80
Right: 76
Top: 14
Bottom: 0
Special: Console
Special: Mapper
Special: Repair
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Camo
Heat sinks: 40
Suspension: Light
Treads: Spiked
Bumpers: None
