Vehicle: Baz
Designer: Smaug
Body: Marauder
Engine: Large Turbine
W#0: T1 Acid Sprayer
W#1: T1 Acid Sprayer
W#2: T2 Acid Sprayer
W#3: T2 Acid Sprayer
Armor Type: Tungsten
Front: 40
Back: 40
Left: 40
Right: 40
Top: 40
Bottom: 40
Special: Console
Special: Mapper
Special: Radar
Special: Ram Plate
Special: HU Display
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 0
Suspension: Active
Treads: Normal
Bumpers: Rubber
