Vehicle: Crispier
Designer: Pond-Skum
Body: Disk
Engine: Breeder Fission
W#0: T1 Tactical Nuke
W#1: T2 Light Machine Gun
W#2: T2 Blast Cannon
Armor Type: Titanium
Front: 83
Back: 58
Left: 58
Right: 58
Top: 30
Bottom: 0
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Rdf
Heat sinks: 10
Suspension: Active
Treads: Chained
Bumpers: Normal
