Vehicle: maggot2
Designer: Wildman
Body: Panzy
Engine: Fusion
W#0: T1 Tactical Nuke
W#1: T2 Pulse Laser
W#2: T2 Pulse Laser
W#3: T3 Pulse Laser
W#4: T3 Pulse Laser
W#5: T4 Pulse Laser
Armor Type: Crumple
Front: 550
Back: 550
Left: 500
Right: 500
Top: 450
Bottom: 424
Special: Console
Special: Mapper
Special: Repair
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Camo
Heat sinks: 35
Suspension: Light
Treads: Spiked
Bumpers: None
