Vehicle: test2
Designer: senft
Body: Delta
Engine: Fusion
W#0: T1 Pocket Rocket
W#1: T2 Pocket Rocket
W#2: T1 Pocket Rocket
W#3: T2 Pocket Rocket
Armor Type: Porcelain
Front: 20
Back: 38
Left: 55
Right: 55
Top: 20
Bottom: 10
Special: Console
Special: Mapper
Special: Radar
Special: HU Display
Special: Stealth
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 0
Suspension: Normal
Treads: Normal
Bumpers: Normal
