Vehicle: THUG
Designer: Wildman
Body: Panzy
Engine: Fuel Cell
W#0: T1 Blast Cannon
W#1: T2 Blast Cannon
W#2: T2 Blast Cannon
W#3: T3 Blast Cannon
W#4: T3 Blast Cannon
W#5: T4 Heavy Machine Gun
Armor Type: Carapice
Front: 100
Back: 70
Left: 70
Right: 71
Top: 14
Bottom: 0
Special: Console
Special: Mapper
Special: Repair
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Tac Link
Special: Camo
Heat sinks: 40
Suspension: Light
Treads: Hover
Bumpers: None
