#!/bin/csh -f
setenv XTANK_DIR       ~stripes/xtank
setenv XTANK_VEHICLES  Vehicles
setenv XTANK_MAZES     Mazes
setenv XTANK_PROGRAMS  Programs

if (`hostname` == sparcee) then
	echo "Debuggin emacs\!"
	xdbx ${XTANK_DIR}/Src/emacs
else
	echo "Debuggin .xtank.sun"
	xdbx ${XTANK_DIR}/.xtank.`arch`
endif
