#!/bin/csh -f
setenv XTANK_DIR       ~stripes/xtank
setenv XTANK_VEHICLES  Vehicles
setenv XTANK_MAZES     Mazes
setenv XTANK_PROGRAMS  Programs

set arch = `arch`

#if (`hostname` == sparcee || `hostname` == emc) then
    #echo "EMACing"
    #${XTANK_DIR}/Src/emacs $*
#else
    echo "Running .xtank.$arch"
    ${XTANK_DIR}/.xtank.$arch $*
#endif
