Vehicle: aaa
Designer: Mr. English
Body: Panzy
Engine: Breeder Fission
W#0: T1 Heavy Machine Gun
W#1: T2 Heavy Machine Gun
W#2: F Heavy Machine Gun
W#3: T3 Acid Sprayer
W#4: T4 Acid Sprayer
W#5: F Acid Sprayer
Armor Type: Steel
Front: 500
Back: 130
Left: 130
Right: 130
Top: 200
Bottom: 50
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 10
Suspension: Active
Treads: Hover
Bumpers: Retro
