Vehicle: Blast
Designer: Mr. Anal
Body: Panzy
Engine: Fuel Cell
W#0: T1 Blast Cannon
W#1: T2 Blast Cannon
W#2: T3 Blast Cannon
W#3: T4 Blast Cannon
W#4: T3 Blast Cannon
W#5: T4 Blast Cannon
Armor Type: Kevlar
Front: 500
Back: 325
Left: 325
Right: 325
Top: 200
Bottom: 165
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 3
Suspension: Normal
Treads: Hover
Bumpers: Normal
