Vehicle: Blast4
Designer: Dr. Love
Body: Rhino
Engine: Fission
W#0: F Heavy Machine Gun
W#1: F Heavy Machine Gun
W#2: F Blast Cannon
W#3: F Blast Cannon
W#4: T2 Blast Cannon
W#5: T1 Blast Cannon
Armor Type: Steel
Front: 350
Back: 95
Left: 120
Right: 120
Top: 100
Bottom: 100
Special: Console
Special: Mapper
Special: HU Display
Special: New Radar
Special: Camo
Heat sinks: 9
Suspension: Active
Treads: Hover
Bumpers: None
