Vehicle: Blast2
Designer: Dr. Love
Body: Rhino
Engine: Breeder Fission
W#0: F Heavy Machine Gun
W#1: F Heavy Machine Gun
W#2: F Heavy Machine Gun
W#3: F Heavy Machine Gun
W#4: T2 Blast Cannon
W#5: T1 Blast Cannon
Armor Type: Steel
Front: 350
Back: 110
Left: 110
Right: 110
Top: 70
Bottom: 130
Special: Console
Special: Mapper
Special: HU Display
Special: New Radar
Special: Camo
Heat sinks: 9
Suspension: Active
Treads: Hover
Bumpers: None
