Vehicle: BrettFun
Designer: Mr. Anal
Body: Panzy
Engine: Fuel Cell
W#0: F Unguided Missle
W#1: F Unguided Missle
W#2: T1 Unguided Missle
W#3: T2 Unguided Missle
W#4: T3 Unguided Missle
W#5: T4 Unguided Missle
Armor Type: Steel
Front: 300
Back: 175
Left: 175
Right: 175
Top: 100
Bottom: 50
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 15
Suspension: Active
Treads: Hover
Bumpers: Retro
