Vehicle: ChiefRamPlate
Designer: Mr. BigNose
Body: Disk
Engine: Breeder Fission
W#0: F Acid Sprayer
W#1: F Acid Sprayer
Armor Type: Kevlar
Front: 210
Back: 160
Left: 120
Right: 120
Top: 60
Bottom: 40
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Rdf
Heat sinks: 0
Suspension: Active
Treads: Hover
Bumpers: Rubber
