Vehicle: FastNuke
Designer: Mr. Anal
Body: Disk
Engine: Fuel Cell
W#0: B Tactical Nuke
W#1: B Tactical Nuke
Armor Type: Steel
Front: 50
Back: 175
Left: 50
Right: 50
Top: 25
Bottom: 25
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 5
Suspension: Active
Treads: Spiked
Bumpers: Retro
