Vehicle: Gnat6
Designer: Katz
Body: Malice
Engine: Fuel Cell
W#0: T1 Acid Sprayer
W#1: T1 Acid Sprayer
W#2: T1 Acid Sprayer
W#3: T1 Acid Sprayer
W#4: T1 Acid Sprayer
W#5: T1 Unguided Missle
Armor Type: Composite
Front: 124
Back: 120
Left: 115
Right: 115
Top: 43
Bottom: 36
Special: Console
Special: Mapper
Special: Radar
Special: Ram Plate
Heat sinks: 2
Suspension: Active
Treads: Normal
Bumpers: Retro
