Vehicle: Gnat3U
Designer: Katz
Body: Malice
Engine: Fuel Cell
W#0: T1 Acid Sprayer
W#1: T1 Acid Sprayer
W#2: T1 Acid Sprayer
W#3: T1 Acid Sprayer
W#4: T1 Unguided Missle
W#5: T1 Unguided Missle
Armor Type: Composite
Front: 124
Back: 118
Left: 114
Right: 114
Top: 22
Bottom: 41
Special: Console
Special: Mapper
Special: Radar
Special: Ram Plate
Heat sinks: 1
Suspension: Active
Treads: Normal
Bumpers: Retro
