Vehicle: Grinder
Designer: Mr. BigNose
Body: Panzy
Engine: Fission
W#0: T1 Heavy Rkt Launcher
W#1: T2 Heavy Rkt Launcher
W#2: T3 Heavy Rkt Launcher
W#3: T4 Heavy Rkt Launcher
Armor Type: Composite
Front: 211
Back: 211
Left: 211
Right: 211
Top: 90
Bottom: 70
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Tac Link
Special: Rdf
Heat sinks: 16
Suspension: Normal
Treads: Normal
Bumpers: Normal
