Vehicle: Hcannon6
Designer: Dr. Love
Body: Panzy
Engine: Breeder Fission
W#0: F Heavy Autocannon
W#1: F Heavy Autocannon
W#2: T1 Heavy Autocannon
W#3: T2 Heavy Autocannon
W#4: T1 Heavy Autocannon
W#5: T2 Heavy Autocannon
Armor Type: Steel
Front: 200
Back: 100
Left: 100
Right: 100
Top: 70
Bottom: 80
Special: Console
Special: Mapper
Special: HU Display
Special: New Radar
Special: Camo
Heat sinks: 28
Suspension: Active
Treads: Hover
Bumpers: Retro
