Vehicle: Hgun6
Designer: Dr. Love
Body: Rhino
Engine: Fission
W#0: F Heavy Machine Gun
W#1: F Heavy Machine Gun
W#2: F Heavy Machine Gun
W#3: F Heavy Machine Gun
W#4: T1 Heavy Machine Gun
W#5: T1 Heavy Machine Gun
Armor Type: Steel
Front: 250
Back: 150
Left: 150
Right: 150
Top: 70
Bottom: 140
Special: Console
Special: Mapper
Special: HU Display
Special: New Radar
Special: Camo
Heat sinks: 9
Suspension: Active
Treads: Hover
Bumpers: None
