Vehicle: Hidden.m
Designer: Mr. English
Body: Malice
Engine: Fuel Cell
W#0: L Anti-Radiation
W#1: R Anti-Radiation
Armor Type: Titanium
Front: 70
Back: 120
Left: 60
Right: 60
Top: 60
Bottom: 60
Special: Console
Special: Mapper
Special: Radar
Special: Ram Plate
Special: HU Display
Special: Stealth
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 0
Suspension: Active
Treads: Smooth
Bumpers: Retro
