Vehicle: Hlauncher6
Designer: Dr. Love
Body: Rhino
Engine: Medium Turbine
W#0: F Heavy Rkt Launcher
W#1: F Heavy Rkt Launcher
W#2: F Heavy Rkt Launcher
W#3: F Heavy Rkt Launcher
W#4: T1 Heavy Rkt Launcher
W#5: T2 Heavy Rkt Launcher
Armor Type: Steel
Front: 300
Back: 60
Left: 100
Right: 100
Top: 70
Bottom: 100
Special: Console
Special: Mapper
Special: HU Display
Special: New Radar
Special: Camo
Heat sinks: 9
Suspension: Active
Treads: Hover
Bumpers: Retro
