Vehicle: Jefticle13
Designer: jeff
Body: Medusa
Engine: Small Electric
W#0: T1 Blast Cannon
W#1: T1 Blast Cannon
W#2: T2 Blast Cannon
W#3: T2 Blast Cannon
W#4: T3 Blast Cannon
W#5: T3 Blast Cannon
Armor Type: Steel
Front: 137
Back: 136
Left: 136
Right: 136
Top: 0
Bottom: 0
Special: Console
Special: Mapper
Special: HU Display
Special: New Radar
Special: Tac Link
Heat sinks: 10
Suspension: Light
Treads: Smooth
Bumpers: Retro
