Vehicle: Launcher6
Designer: Dr. Love
Body: Panzy
Engine: Breeder Fission
W#0: F Heavy Rkt Launcher
W#1: F Heavy Rkt Launcher
W#2: T4 Heavy Rkt Launcher
W#3: T3 Heavy Rkt Launcher
W#4: T1 Heavy Rkt Launcher
W#5: T2 Heavy Rkt Launcher
Armor Type: Steel
Front: 250
Back: 95
Left: 110
Right: 110
Top: 130
Bottom: 70
Special: Console
Special: Mapper
Special: HU Display
Special: New Radar
Special: Camo
Heat sinks: 18
Suspension: Active
Treads: Hover
Bumpers: Retro
