Vehicle: Lgun6
Designer: Dr. Love
Body: Rhino
Engine: Fission
W#0: F Light Machine Gun
W#1: F Light Machine Gun
W#2: F Light Machine Gun
W#3: F Light Machine Gun
W#4: T1 Light Machine Gun
W#5: T2 Light Machine Gun
Armor Type: Steel
Front: 500
Back: 200
Left: 90
Right: 90
Top: 130
Bottom: 40
Special: Console
Special: Mapper
Special: HU Display
Special: New Radar
Special: Tac Link
Special: Camo
Heat sinks: 0
Suspension: Active
Treads: Hover
Bumpers: None
