Vehicle: Light6
Designer: Dr. Love
Body: Malice
Engine: Breeder Fission
W#0: F Light Machine Gun
W#1: F Light Machine Gun
W#2: F Light Machine Gun
W#3: F Light Machine Gun
W#4: T1 Light Machine Gun
W#5: T1 Light Machine Gun
Armor Type: Steel
Front: 120
Back: 90
Left: 85
Right: 85
Top: 70
Bottom: 45
Special: Console
Special: Mapper
Special: HU Display
Special: New Radar
Special: Tac Link
Special: Camo
Heat sinks: 0
Suspension: Active
Treads: Smooth
Bumpers: Retro
