Vehicle: Magic1
Designer: 
Body: Medusa
Engine: Large Turbine
W#0: T1 Heavy Machine Gun
W#1: T1 Heavy Machine Gun
W#2: T2 Heavy Machine Gun
W#3: T2 Heavy Machine Gun
W#4: T3 Heavy Machine Gun
W#5: T3 Heavy Machine Gun
Armor Type: Kevlar
Front: 135
Back: 135
Left: 135
Right: 135
Top: 175
Bottom: 142
Special: Console
Special: Mapper
Special: Repair
Special: Ram Plate
Special: HU Display
Special: Stealth
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 4
Suspension: Light
Treads: Hover
Bumpers: Retro
