Vehicle: Miner
Designer: Mr. Anal
Body: Rhino
Engine: Fuel Cell
W#0: B Mine Layer
W#1: B Oil Slick
W#2: L Mine Layer
W#3: R Mine Layer
W#4: L Mine Layer
W#5: R Mine Layer
Armor Type: Steel
Front: 175
Back: 185
Left: 150
Right: 150
Top: 150
Bottom: 69
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 5
Suspension: Active
Treads: Hover
Bumpers: Retro
