Vehicle: Minute Man II
Designer: Gordon
Body: Medusa
Engine: Small Electric
W#0: T1 Tactical Nuke
W#1: T3 Tactical Nuke
W#2: T2 Heavy Machine Gun
W#3: T2 Heavy Machine Gun
Armor Type: Titanium
Front: 80
Back: 80
Left: 80
Right: 80
Top: 80
Bottom: 80
Special: Console
Special: Mapper
Special: Repair
Special: New Radar
Special: Tac Link
Special: Camo
Heat sinks: 7
Suspension: Light
Treads: Spiked
Bumpers: None
