Vehicle: Pain2
Designer: Cannon Fodde
Body: Disk
Engine: Super Electric
W#0: B Tactical Nuke
W#1: B Tactical Nuke
Armor Type: Kevlar
Front: 150
Back: 150
Left: 150
Right: 150
Top: 97
Bottom: 80
Special: Console
Special: Mapper
Special: Radar
Special: Ram Plate
Special: HU Display
Special: Stealth
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 0
Suspension: Normal
Treads: Normal
Bumpers: Normal
