Vehicle: pain2
Designer: 
Body: Hexo
Engine: Large Turbine
W#0: T1 Blast Cannon
Armor Type: Tungsten
Front: 15
Back: 15
Left: 15
Right: 15
Top: 4
Bottom: 4
Special: Console
Special: Mapper
Special: Repair
Special: Ram Plate
Special: HU Display
Special: Stealth
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 0
Suspension: Light
Treads: Hover
Bumpers: Retro
