Vehicle: pain1
Designer: 
Body: Medusa
Engine: Large Turbine
W#0: T1 Blast Cannon
W#1: T2 Blast Cannon
W#2: T3 Blast Cannon
Armor Type: Kevlar
Front: 120
Back: 120
Left: 120
Right: 120
Top: 160
Bottom: 143
Special: Console
Special: Mapper
Special: Repair
Special: Ram Plate
Special: HU Display
Special: Stealth
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 6
Suspension: Light
Treads: Hover
Bumpers: Retro
