Vehicle: Pain1
Designer: Mr. Anal
Body: Panzy
Engine: Fuel Cell
W#0: T1 Heavy Mortar
W#1: T2 Heavy Mortar
W#2: T3 Heavy Mortar
W#3: T4 Heavy Mortar
W#4: T1 Heat Seeker
W#5: T2 Heat Seeker
Armor Type: Kevlar
Front: 275
Back: 275
Left: 275
Right: 275
Top: 175
Bottom: 165
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 3
Suspension: Normal
Treads: Normal
Bumpers: Normal
