Vehicle: Pain3
Designer: Cannon Fodde
Body: Disk
Engine: Large Turbine
W#0: B Tactical Nuke
W#1: B Tactical Nuke
W#2: T1 Heavy Mortar
Armor Type: Kevlar
Front: 119
Back: 119
Left: 119
Right: 119
Top: 97
Bottom: 80
Special: Console
Special: Mapper
Special: Repair
Special: Ram Plate
Special: HU Display
Special: Stealth
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 0
Suspension: Light
Treads: Hover
Bumpers: Retro
