Vehicle: Pocket6
Designer: Dr. Love
Body: Panzy
Engine: Fission
W#0: F Pocket Rocket
W#1: F Pocket Rocket
W#2: T4 Pocket Rocket
W#3: T3 Pocket Rocket
W#4: T1 Pocket Rocket
W#5: T2 Pocket Rocket
Armor Type: Steel
Front: 180
Back: 90
Left: 80
Right: 80
Top: 130
Bottom: 69
Special: Console
Special: Mapper
Special: HU Display
Special: New Radar
Special: Camo
Heat sinks: 20
Suspension: Active
Treads: Hover
Bumpers: Retro
