Vehicle: RadSpecial
Designer: Mr. Anal
Body: Panzy
Engine: Fuel Cell
W#0: L Anti-Radiation
W#1: R Anti-Radiation
W#2: L Anti-Radiation
W#3: R Anti-Radiation
W#4: L Anti-Radiation
W#5: R Anti-Radiation
Armor Type: Tungsten
Front: 175
Back: 125
Left: 125
Right: 125
Top: 75
Bottom: 20
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 5
Suspension: Active
Treads: Hover
Bumpers: Retro
