Vehicle: Smack
Designer: Platypus Man
Body: Tiger
Engine: Breeder Fission
W#0: F Autocannon
W#1: T1 Autocannon
W#2: F Autocannon
Armor Type: Kevlar
Front: 300
Back: 200
Left: 75
Right: 75
Top: 101
Bottom: 20
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 3
Suspension: Active
Treads: Hover
Bumpers: Retro
