Vehicle: Splat
Designer: Platypus Man
Body: Panzy
Engine: Breeder Fission
W#0: T1 Heavy Mortar
W#1: T2 Heavy Mortar
W#2: T3 Heavy Mortar
W#3: T4 Heavy Mortar
W#4: F Autocannon
W#5: F Autocannon
Armor Type: Steel
Front: 240
Back: 200
Left: 200
Right: 200
Top: 200
Bottom: 97
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Camo
Special: Rdf
Heat sinks: 4
Suspension: Active
Treads: Hover
Bumpers: Retro
