Vehicle: Test
Designer: Mr. BigNose
Body: Medusa
Engine: Fission
W#0: F TeleGuided
W#1: T1 TeleGuided
W#2: B Land Torpedo
W#3: L Anti-Radiation
Armor Type: Kevlar
Front: 90
Back: 90
Left: 90
Right: 90
Top: 40
Bottom: 30
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Stealth
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 3
Suspension: Normal
Treads: Normal
Bumpers: Normal
