Vehicle: Thump
Designer: Mr. BigNose
Body: Medusa
Engine: Fission
W#0: T1 Heavy Autocannon
W#1: T2 Heavy Autocannon
W#2: T3 Heavy Autocannon
Armor Type: Composite
Front: 105
Back: 95
Left: 95
Right: 95
Top: 60
Bottom: 40
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Tac Link
Special: Rdf
Heat sinks: 10
Suspension: Heavy
Treads: Smooth
Bumpers: Retro
