Vehicle: TowHell2
Designer: Mr. Anal
Body: Panzy
Engine: Fuel Cell
W#0: T1 Heavy Mortar
W#1: T2 Heavy Mortar
W#2: T3 Heavy Mortar
W#3: T4 Heavy Mortar
W#4: T3 Heavy Mortar
W#5: T4 Heavy Mortar
Armor Type: Kevlar
Front: 250
Back: 250
Left: 250
Right: 250
Top: 150
Bottom: 165
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 6
Suspension: Normal
Treads: Hover
Bumpers: Normal
