Vehicle: TowHell3
Designer: Mr. Anal
Body: Panzy
Engine: Fuel Cell
W#0: T1 TOW Missile
W#1: T2 TOW Missile
W#2: F TOW Missile
W#3: F TOW Missile
W#4: T3 TOW Missile
W#5: T4 TOW Missile
Armor Type: Kevlar
Front: 275
Back: 275
Left: 275
Right: 275
Top: 175
Bottom: 165
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 3
Suspension: Normal
Treads: Hover
Bumpers: Normal
