Vehicle: Trix
Designer: Platypus Man
Body: Tiger
Engine: Fuel Cell
W#0: T1 Heavy Mortar
W#1: F Heavy Autocannon
W#2: T1 Heavy Mortar
W#3: F Heavy Autocannon
Armor Type: Steel
Front: 117
Back: 110
Left: 100
Right: 100
Top: 70
Bottom: 50
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 5
Suspension: Active
Treads: Hover
Bumpers: Retro
