Vehicle: Truck
Designer: Mr.BigNose
Body: Panzy
Engine: Breeder Fission
W#0: T1 Heat Seeker
W#1: T2 Heat Seeker
W#2: T3 Heat Seeker
W#3: F Acid Sprayer
W#4: F Acid Sprayer
W#5: F Acid Sprayer
Armor Type: Kevlar
Front: 370
Back: 290
Left: 210
Right: 210
Top: 80
Bottom: 60
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Tac Link
Special: Rdf
Heat sinks: 9
Suspension: Heavy
Treads: Smooth
Bumpers: Normal
