Vehicle: Vanguard
Designer: tmdonahu
Body: Marauder
Engine: Fuel Cell
W#0: T1 Heavy Autocannon
W#1: T2 Heavy Autocannon
Armor Type: Compound Steel
Front: 60
Back: 60
Left: 60
Right: 60
Top: 45
Bottom: 40
Special: Console
Special: Mapper
Special: Radar
Special: HU Display
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 8
Suspension: Active
Treads: Normal
Bumpers: Rubber
