Vehicle: vvv
Designer: Mr. English
Body: Marauder
Engine: Breeder Fission
W#0: T1 Blast Cannon
W#1: T2 Blast Cannon
Armor Type: Kevlar
Front: 280
Back: 200
Left: 100
Right: 100
Top: 100
Bottom: 100
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 0
Suspension: Active
Treads: Smooth
Bumpers: Retro
