Vehicle: xxx
Designer: Mr. English
Body: Medusa
Engine: Fuel Cell
W#0: T1 Blast Cannon
W#1: T2 Blast Cannon
W#2: T3 Blast Cannon
Armor Type: Tungsten
Front: 100
Back: 100
Left: 80
Right: 80
Top: 30
Bottom: 30
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Stealth
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 0
Suspension: Active
Treads: Hover
Bumpers: Retro
