Vehicle: yyy
Designer: Mr. English
Body: Medusa
Engine: Fuel Cell
W#0: T1 Blast Cannon
W#1: T2 Blast Cannon
W#2: T3 Blast Cannon
Armor Type: Kevlar
Front: 250
Back: 250
Left: 190
Right: 190
Top: 170
Bottom: 70
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: Stealth
Special: Navigation
Special: New Radar
Special: Tac Link
Special: Camo
Special: Rdf
Heat sinks: 0
Suspension: Active
Treads: Hover
Bumpers: Retro
