Vehicle: Zot
Designer: Mr. BigNose
Body: Marauder
Engine: Breeder Fission
W#0: T1 Pulse Laser
W#1: T1 Pulse Laser
W#2: T2 Pulse Laser
W#3: T2 Pulse Laser
Armor Type: Composite
Front: 90
Back: 90
Left: 95
Right: 95
Top: 66
Bottom: 30
Special: Console
Special: Mapper
Special: Ram Plate
Special: HU Display
Special: New Radar
Special: Tac Link
Special: Rdf
Heat sinks: 6
Suspension: Heavy
Treads: Smooth
Bumpers: Rubber
