#
# This makefile describes how to make the xtank utilities
#

x10tox11: x10tox11.c
	cc x10tox11.c -o x10tox11

x11tox10: x11tox10.c
	cc x11tox10.c -o x11tox10

objcon: objcon.c
	cc objcon.c -o objcon

r4: r4.c
	cc r4.c -o r4 -lm

objcreate: objcreate.c
	cc objcreate.c -o objcreate -lm

r1to3: r1to3.c
	cc r1to3.c -o r1to3 -lm

trim: trim.c
	cc trim.c -o trim

objview: objview.c
	cc objview.c -o objview /usr/lib/X10/libX.a
