/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: /usr/fsys/odin/a/vern/flex/RCS/flex.skel,v 2.16 90/08/03 14:09:36 vern Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
#else
#include <stdlib.h>
#endif	/* __GNUC__ */

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* we can't get here if it's an ANSI C compiler, or a C++ compiler,
 * so it's got to be a K&R compiler, and therefore there's no standard
 * place from which to include these definitions
 */
char *malloc();
int free();
int read();
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR char
# line 1 "setups.l"
#define INITIAL 0
# line 2 "setups.l"

#include <stdio.h>
#include <string.h>

#include "xtank.h"
#include "vehicle.h"
#include "setup.h"
#include "globals.h"
#include "team.h"
/* For "UNDEFINED" */
#include "interface.h"
#include "terminal.h"

#define BUFLEN 256
#define SEP ",\t"

extern char *games_entries[];
extern Settings settings;
extern int num_terminals;
extern Terminal *terminal[];

char *yval(), *strtoke();
void cv_str(), cv_kw2i(), cv_bool(), cv_int(), cv_flt(), cv_maze();

# line 34 "setups.l"

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters*/
    int yy_buf_size;	

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 46
typedef int yy_state_type;
static const short int yy_accept[597] =
    {   0,
       44,   44,   46,   44,    1,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,

       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   43,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,

       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,    4,   44,    3,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   42,   44,   44,   44,   44,   44,

       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
        8,   44,   44,   44,   44,   44,   44,   41,   44,   44,
        9,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   11,   44,   15,   16,   44,   44,   44,   44,
       44,   44,    7,   44,    6,   44,   44,   44,   44,   44,

       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   35,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   40,
       44,   44,   44,   33,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   17,   44,
       44,   44,   44,   44,   44,   44,    2,   44,   10,   34,
       44,   44,   44,   44,   44,   44,   44,   44,   12,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   31,   44,   44,   44,   44,   44,

       44,   44,   44,   44,   44,   44,   44,   30,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       32,   44,   19,   44,   44,   44,   44,   44,    5,   26,
       44,   44,   39,   37,   44,   44,   44,   44,   44,   44,
       44,   44,   28,   44,   44,   44,   44,   36,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   25,   14,
       38,   44,   44,   44,   18,   44,   44,   44,   44,   44,
       44,   44,   44,   29,   13,   44,   44,   44,   44,   22,
       44,   44,   44,   44,   44,   27,   44,   44,   20,   44,
       24,   44,   23,   44,   21,    0

    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    6,    1,
        1,    1,    1,    1,    1,    7,    1,    8,    9,   10,
       11,   12,   10,   13,   10,   10,   10,   14,    1,    1,
        1,    1,    1,    1,   15,   16,   17,   18,    1,   19,
       20,   21,    1,    1,    1,    1,   22,   23,   24,   25,
        1,   26,   27,   28,   29,   30,   31,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,    1,   41,   42,   43,   44,
       45,   46,    1,   47,   48,   49,   50,   51,   52,   53,
       54,   55,    1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[56] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const short int yy_base[604] =
    {   0,
        0,   28, 1026,    0, 1027, 1020,  979,  978,  982,  971,
      988,  987,    4,   10,   29,   27,    0,    1,  976,    0,
      968,    0,    0,  963,  972,   27,  972,  970,   13,  969,
       18,  962,  966,  955,  976,  967,  961,   31,  971,  971,
      956,  957,  961,  956,   38,  950,  951,  953,  964,    6,
      991,  951,  956,  958,  949,  954,  985,  952,  951,   12,
      943,  939,  948,  979,  928,  937,  942,    3,  930,  933,
      932,  931,  941,  928,  932,  929,  935,  930,  965,  924,
      923,    0,  918,  929,  924,  959,  958,  947,  945,  945,
      909,  925,  920,  923,  909,  906,  924,  915,  901,  902,

      929,  898,  914,  911,  895,  901,  901,  937,  892,  935,
      892,  894,  916,  895,  893,   19,  891,  888,  897,   64,
      908,   22,  882,   23,  896,  892,  894,  883,  876,  919,
      877,  874,  916,  887,  878,  877,  869,  876,  866,  871,
      876,  892,  896,  882,  863,  875,  861,  861,  890,  900,
       84,  857,  852,  850,  867,  851,  861,  850,  859,  862,
       91,  850,   92,  854,  859,  843,  885,  839,  860,  882,
      881,  868,  840,  835,  830,  831,  843,  874,  873,  829,
      828,   95,  840,  826,  823,  839,  832,   96, 1027,  817,
      836,  825,  823,  825,  832,  827,  820,  815,  857,   99,

      814,  855,  102,  809,  809,  841,  835,  849,  810,  826,
      822,  799,  834,  811,  810,  831,  795,  825,  815,  837,
      800,  105,  794,  789,  801,  794,  831,  106,  799,  784,
      783,  799,  796,  780,  792,  791,  812, 1027,  778, 1027,
      810,  809,  109,  775,  794,  775,  777,  782,  775,  110,
      802,  811,  114,  800,  768,  766,  780,  776,  806,  117,
      761,  803,  802,  757,  777,  794,  757,  756,  746,  761,
      749,  783,  761,  749,  120,  790,  121,  124,  125,  753,
      743,  739,  758,  747,  746,  128,  133,  769,  134,  137,
      742,  749,  752,  734, 1027,  746,  125,  757,  776,  745,

      766,  725,  729,  761,  738,  733,  143,  758,  726,  146,
      743,  154,  157,  766,  734,  720,  731,  711,  728,  727,
      759,  165,  168,  721,  757,  171,  753,  722,  715,  716,
      741,  710,  706,  707,  699,  726,  700,  730,  694,  720,
      147,  716,  682,  179,  180,  670,  713,  679,  702,  701,
     1027,  654,  666,  649,  679,  646,  642, 1027,  678,  632,
     1027,  674,  618,  631,  621,  610,  191,  600,  608,  648,
      600,  599,  595,  629,  617,  192,  195,  196,  586,  206,
      218,  580, 1027,  589, 1027, 1027,  580,  575,  566,  208,
      565,  561, 1027,  574, 1027,  603,  583,  548,  549,  230,

      580,  540,   61,  578,  532,  534,  554,  219,  233,  237,
      249,  545, 1027,  260,  271,  544,  515,  511,  510,  503,
      283,  499,  531,  521,  503,  250,  517,  508,  518,  492,
      508,  475,  474,  489,  447,  486,  496,  286,  495, 1027,
      297,  262,  308, 1027,  319,  263,  454,  445,  439,  472,
      474,  427,  273,  299,  435,  331,  310,  311, 1027,  422,
      129,  416,  433,  419,  442,  321, 1027,  342, 1027, 1027,
      353,  365,  376,  388,  440,  431,  405,  322, 1027,  419,
      391,  399,  388,  402,  414,  426,  417,  384,  370,  349,
      351,  359,  332,  438, 1027,  449,  460,  471,  369,  344,

      355,  357,  483,  356,  344,  335,  323, 1027,  494,  505,
      516,  287,  243,  257,  239,  262,  214,  528,  530,  541,
     1027,  552, 1027,  564,  567,  366,  578,  590, 1027, 1027,
      378,  592, 1027, 1027,  603,  211,  195,  200,  204,  379,
      219,  222, 1027,  614,  221,  625,  637, 1027,  648,  208,
      660,  662,  148,  154,  172,  143,  674,  400, 1027, 1027,
     1027,  676,  687,  698, 1027,  175,  160,  139,  415,  150,
      157,  710,  712, 1027, 1027,  427,  104,  724,  439, 1027,
      128,  727,  103,   87,  735, 1027,   75,  451, 1027,   74,
     1027,  738, 1027,   66, 1027, 1027,  747,   40,   28,   27,

        5,    4,    0
    } ;

static const short int yy_def[604] =
    {   0,
      597,  597,  596,  598,  596,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,

      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  599,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  599,
      599,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      600,  598,  601,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  596,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  600,  600,

      598,  601,  601,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  602,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  596,  598,  596,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  602,  602,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  603,  598,  598,  598,  598,
      598,  598,  598,  598,  596,  598,  598,  598,  598,  598,

      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      603,  603,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      596,  598,  598,  598,  598,  598,  598,  596,  598,  598,
      596,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  596,  598,  596,  596,  598,  598,  598,  598,
      598,  598,  596,  598,  596,  598,  598,  598,  598,  598,

      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  596,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  596,
      598,  598,  598,  596,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  596,  598,
      598,  598,  598,  598,  598,  598,  596,  598,  596,  596,
      598,  598,  598,  598,  598,  598,  598,  598,  596,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  596,  598,  598,  598,  598,  598,

      598,  598,  598,  598,  598,  598,  598,  596,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      596,  598,  596,  598,  598,  598,  598,  598,  596,  596,
      598,  598,  596,  596,  598,  598,  598,  598,  598,  598,
      598,  598,  596,  598,  598,  598,  598,  596,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  596,  596,
      596,  598,  598,  598,  596,  598,  598,  598,  598,  598,
      598,  598,  598,  596,  596,  598,  598,  598,  598,  596,
      598,  598,  598,  598,  598,  596,  598,  598,  596,  598,
      596,  598,  596,  598,  596,    0,  596,  596,  596,  596,

      596,  596,  596
    } ;

static const short int yy_nxt[1083] =
    {   0,
      321,  116,    5,  116,  259,  202,  101,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   82,
      151,   60,  151,  161,  163,  161,  163,  199,  150,    6,
        5,   47,   44,   41,  102,   30,   45,   92,   42,   48,
       22,   43,   93,    7,    8,    9,   10,   11,   31,   12,
       13,   14,   15,   16,   17,   18,   19,    6,   20,   32,
       34,   33,   38,   53,   61,   57,   39,   58,  595,   76,
       35,   40,   68,   36,   54,   37,  593,  591,   69,   77,
       21,  155,  156,  432,  157,  151,  189,  151,  433,  589,
      158,  159,  200,  203,  200,  203,  222,  228,  222,  228,

      200,  238,  200,  203,  240,  203,  260,  228,  260,  228,
      279,  286,  279,  286,  266,  289,  588,  289,  260,  295,
      260,  310,  312,  310,  312,  313,  279,  313,  279,  322,
      586,  322,  314,  314,  323,  289,  323,  289,  326,  332,
      326,  325,  325,  333,  344,  583,  344,  310,  377,  310,
      377,  488,  334,  347,  347,  312,  489,  312,  313,  580,
      313,  349,  349,  579,  350,  350,  322,  358,  322,  323,
      577,  323,  326,  576,  326,  359,  359,  575,  362,  362,
      344,  381,  344,  381,  570,  569,  380,  380,  380,  380,
      380,  380,  400,  409,  400,  409,  377,  411,  377,  411,

      568,  567,  410,  410,  410,  410,  410,  410,  413,  421,
      565,  421,  414,  380,  380,  380,  380,  380,  380,  381,
      438,  381,  438,  560,  559,  415,  415,  415,  415,  415,
      415,  400,  558,  400,  409,  556,  409,  429,  429,  440,
      439,  439,  555,  554,  410,  410,  410,  410,  410,  410,
      411,  456,  411,  456,  553,  541,  441,  441,  441,  441,
      441,  441,  413,  472,  474,  472,  474,  443,  443,  443,
      443,  443,  443,  444,  481,  540,  481,  445,  415,  415,
      415,  415,  415,  415,  421,  539,  421,  438,  538,  438,
      451,  451,  537,  468,  468,  468,  468,  468,  468,  470,

      482,  536,  482,  471,  441,  441,  441,  441,  441,  441,
      413,  485,  486,  485,  486,  443,  443,  443,  443,  443,
      443,  444,  494,  503,  494,  503,  473,  473,  473,  473,
      473,  473,  456,  518,  456,  518,  531,  530,  484,  484,
      484,  484,  484,  484,  495,  524,  529,  524,  496,  468,
      468,  468,  468,  468,  468,  470,  525,  528,  525,  528,
      497,  497,  497,  497,  497,  497,  472,  547,  472,  547,
      526,  523,  498,  498,  498,  498,  498,  498,  444,  551,
      557,  551,  557,  473,  473,  473,  473,  473,  473,  474,
      517,  474,  481,  516,  481,  499,  499,  515,  505,  505,

      482,  572,  482,  572,  508,  514,  506,  506,  509,  484,
      484,  484,  484,  484,  484,  485,  578,  485,  578,  513,
      512,  510,  510,  510,  510,  510,  510,  486,  582,  486,
      582,  507,  504,  511,  511,  511,  511,  511,  511,  494,
      585,  494,  585,  502,  501,  519,  519,  519,  519,  519,
      519,  495,  592,  500,  592,  493,  520,  520,  520,  520,
      520,  520,  470,  492,  491,  490,  487,  497,  497,  497,
      497,  497,  497,  521,  483,  480,  479,  522,  498,  498,
      498,  498,  498,  498,  503,  478,  503,  477,  476,  475,
      527,  527,  527,  527,  527,  527,  508,  469,  467,  466,

      465,  532,  532,  532,  532,  532,  532,  533,  464,  463,
      462,  461,  510,  510,  510,  510,  510,  510,  534,  460,
      459,  458,  535,  511,  511,  511,  511,  511,  511,  518,
      457,  518,  543,  455,  454,  542,  542,  519,  519,  519,
      519,  519,  519,  495,  453,  452,  450,  449,  520,  520,
      520,  520,  520,  520,  521,  448,  447,  446,  442,  544,
      544,  544,  544,  544,  544,  524,  437,  524,  525,  436,
      525,  545,  545,  435,  546,  546,  546,  546,  546,  546,
      548,  434,  431,  430,  549,  527,  527,  527,  527,  527,
      527,  528,  428,  528,  508,  427,  426,  550,  550,  532,

      532,  532,  532,  532,  532,  534,  425,  424,  423,  422,
      552,  552,  552,  552,  552,  552,  521,  420,  419,  418,
      417,  544,  544,  544,  544,  544,  544,  561,  416,  412,
      408,  562,  546,  546,  546,  546,  546,  546,  547,  407,
      547,  406,  405,  404,  563,  563,  563,  563,  563,  563,
      548,  403,  402,  401,  399,  564,  564,  564,  564,  564,
      564,  551,  398,  551,  534,  397,  396,  566,  566,  552,
      552,  552,  552,  552,  552,  557,  395,  557,  561,  394,
      393,  571,  571,  573,  573,  573,  573,  573,  573,  574,
      392,  391,  390,  389,  563,  563,  563,  563,  563,  563,

      548,  388,  387,  386,  385,  564,  564,  564,  564,  564,
      564,  572,  384,  572,  561,  383,  382,  581,  581,  573,
      573,  573,  573,  573,  573,  578,  379,  578,  582,  378,
      582,  584,  584,  376,  587,  587,  585,  375,  585,  592,
      374,  592,  590,  590,  373,  594,  594,    4,    4,  372,
      371,  370,  369,  368,  367,  366,  365,  364,  363,  361,
      360,  358,  357,  356,  355,  354,  353,  352,  351,  348,
      346,  345,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  331,  330,  329,  328,  327,  324,  320,  319,  318,
      317,  316,  315,  311,  309,  308,  307,  306,  305,  304,

      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  288,  287,  285,  284,  283,  282,
      281,  280,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  265,  264,  263,  262,  261,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  227,
      226,  225,  224,  223,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  201,  198,  197,  196,  195,  194,  193,  192,

      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  167,  166,  165,  164,  162,  160,
      154,  153,  152,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  121,  120,  119,  118,  117,  115,  114,  113,  112,
      111,  110,  109,  108,  107,  106,  105,  104,  103,  100,
       99,   98,   97,   96,   95,   94,   91,   90,   89,   88,
       87,   86,   85,   84,   83,   81,   80,   79,   78,   75,

       74,   73,   72,   71,   70,   67,   66,   65,   64,   63,
       62,   59,   56,   55,   52,   51,   49,   46,   29,   28,
       27,   26,   25,   24,   23,  596,    3,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596
    } ;

static const short int yy_chk[1083] =
    {   0,
      603,   82,    1,   82,  602,  601,   68,   23,   23,   23,
       23,   23,   23,   50,   50,   50,   50,   50,   50,   50,
      116,   31,  116,  122,  124,  122,  124,  600,  599,    1,
        2,   20,   18,   17,   68,   13,   18,   60,   17,   20,
      598,   17,   60,    2,    2,    2,    2,    2,   13,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,   14,
       15,   14,   16,   26,   31,   29,   16,   29,  594,   45,
       15,   16,   38,   15,   26,   15,  590,  587,   38,   45,
        2,  120,  120,  403,  120,  151,  151,  151,  403,  584,
      120,  120,  161,  163,  161,  163,  182,  188,  182,  188,

      200,  200,  200,  203,  203,  203,  222,  228,  222,  228,
      243,  250,  243,  250,  228,  253,  583,  253,  260,  260,
      260,  275,  277,  275,  277,  278,  279,  278,  279,  286,
      581,  286,  279,  279,  287,  289,  287,  289,  290,  297,
      290,  289,  289,  297,  307,  577,  307,  310,  341,  310,
      341,  461,  297,  310,  310,  312,  461,  312,  313,  571,
      313,  312,  312,  570,  313,  313,  322,  322,  322,  323,
      568,  323,  326,  567,  326,  323,  323,  566,  326,  326,
      344,  345,  344,  345,  556,  555,  344,  344,  344,  344,
      344,  344,  367,  376,  367,  376,  377,  378,  377,  378,

      554,  553,  377,  377,  377,  377,  377,  377,  380,  390,
      550,  390,  380,  380,  380,  380,  380,  380,  380,  381,
      408,  381,  408,  545,  542,  381,  381,  381,  381,  381,
      381,  400,  541,  400,  409,  539,  409,  400,  400,  410,
      409,  409,  538,  537,  410,  410,  410,  410,  410,  410,
      411,  426,  411,  426,  536,  517,  411,  411,  411,  411,
      411,  411,  414,  442,  446,  442,  446,  414,  414,  414,
      414,  414,  414,  415,  453,  516,  453,  415,  415,  415,
      415,  415,  415,  415,  421,  515,  421,  438,  514,  438,
      421,  421,  513,  438,  438,  438,  438,  438,  438,  441,

      454,  512,  454,  441,  441,  441,  441,  441,  441,  441,
      443,  457,  458,  457,  458,  443,  443,  443,  443,  443,
      443,  445,  466,  478,  466,  478,  445,  445,  445,  445,
      445,  445,  456,  493,  456,  493,  507,  506,  456,  456,
      456,  456,  456,  456,  468,  500,  505,  500,  468,  468,
      468,  468,  468,  468,  468,  471,  501,  504,  501,  504,
      471,  471,  471,  471,  471,  471,  472,  526,  472,  526,
      502,  499,  472,  472,  472,  472,  472,  472,  473,  531,
      540,  531,  540,  473,  473,  473,  473,  473,  473,  474,
      492,  474,  481,  491,  481,  474,  474,  490,  481,  481,

      482,  558,  482,  558,  484,  489,  482,  482,  484,  484,
      484,  484,  484,  484,  484,  485,  569,  485,  569,  488,
      487,  485,  485,  485,  485,  485,  485,  486,  576,  486,
      576,  483,  480,  486,  486,  486,  486,  486,  486,  494,
      579,  494,  579,  477,  476,  494,  494,  494,  494,  494,
      494,  496,  588,  475,  588,  465,  496,  496,  496,  496,
      496,  496,  497,  464,  463,  462,  460,  497,  497,  497,
      497,  497,  497,  498,  455,  452,  451,  498,  498,  498,
      498,  498,  498,  498,  503,  450,  503,  449,  448,  447,
      503,  503,  503,  503,  503,  503,  509,  439,  437,  436,

      435,  509,  509,  509,  509,  509,  509,  510,  434,  433,
      432,  431,  510,  510,  510,  510,  510,  510,  511,  430,
      429,  428,  511,  511,  511,  511,  511,  511,  511,  518,
      427,  518,  519,  425,  424,  518,  518,  519,  519,  519,
      519,  519,  519,  520,  423,  422,  420,  419,  520,  520,
      520,  520,  520,  520,  522,  418,  417,  416,  412,  522,
      522,  522,  522,  522,  522,  524,  407,  524,  525,  406,
      525,  524,  524,  405,  525,  525,  525,  525,  525,  525,
      527,  404,  402,  401,  527,  527,  527,  527,  527,  527,
      527,  528,  399,  528,  532,  398,  397,  528,  528,  532,

      532,  532,  532,  532,  532,  535,  396,  394,  392,  391,
      535,  535,  535,  535,  535,  535,  544,  389,  388,  387,
      384,  544,  544,  544,  544,  544,  544,  546,  382,  379,
      375,  546,  546,  546,  546,  546,  546,  546,  547,  374,
      547,  373,  372,  371,  547,  547,  547,  547,  547,  547,
      549,  370,  369,  368,  366,  549,  549,  549,  549,  549,
      549,  551,  365,  551,  552,  364,  363,  551,  551,  552,
      552,  552,  552,  552,  552,  557,  362,  557,  562,  360,
      359,  557,  557,  562,  562,  562,  562,  562,  562,  563,
      357,  356,  355,  354,  563,  563,  563,  563,  563,  563,

      564,  353,  352,  350,  349,  564,  564,  564,  564,  564,
      564,  572,  348,  572,  573,  347,  346,  572,  572,  573,
      573,  573,  573,  573,  573,  578,  343,  578,  582,  342,
      582,  578,  578,  340,  582,  582,  585,  339,  585,  592,
      338,  592,  585,  585,  337,  592,  592,  597,  597,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  325,
      324,  321,  320,  319,  318,  317,  316,  315,  314,  311,
      309,  308,  306,  305,  304,  303,  302,  301,  300,  299,
      298,  296,  294,  293,  292,  291,  288,  285,  284,  283,
      282,  281,  280,  276,  274,  273,  272,  271,  270,  269,

      268,  267,  266,  265,  264,  263,  262,  261,  259,  258,
      257,  256,  255,  254,  252,  251,  249,  248,  247,  246,
      245,  244,  242,  241,  239,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  227,  226,  225,  224,  223,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  202,  201,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  187,
      186,  185,  184,  183,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  162,  160,  159,  158,  157,  156,  155,  154,

      153,  152,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  123,  121,
      119,  118,  117,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       98,   97,   96,   95,   94,   93,   92,   91,   90,   89,
       88,   87,   86,   85,   84,   83,   81,   80,   79,   78,
       77,   76,   75,   74,   73,   72,   71,   70,   69,   67,
       66,   65,   64,   63,   62,   61,   59,   58,   57,   56,
       55,   54,   53,   52,   51,   49,   48,   47,   46,   44,

       43,   42,   41,   40,   39,   37,   36,   35,   34,   33,
       32,   30,   28,   27,   25,   24,   21,   19,   12,   11,
       10,    9,    8,    7,    6,    3,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;




    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
	if ( yy_bp[-1] == '\n' )
	    ++yy_current_state;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 597 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 596 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
# line 36 "setups.l"
{ }
	YY_BREAK
case 2:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 37 "setups.l"
{ }
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 38 "setups.l"
{ cv_maze(yval(), &settings.mdesc); }
	YY_BREAK
case 4:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 39 "setups.l"
{ cv_kw2i(yval(), &settings.si.game,games_entries);}
	YY_BREAK
case 5:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 40 "setups.l"
{ cv_bool(yval(), &settings.point_bullets); }
	YY_BREAK
case 6:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 41 "setups.l"
{ cv_bool(yval(), &settings.si.ricochet); }
	YY_BREAK
case 7:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 42 "setups.l"
{ cv_bool(yval(), &settings.si.rel_shoot); }
	YY_BREAK
case 8:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 43 "setups.l"
{ cv_bool(yval(), &settings.si.no_wear); }
	YY_BREAK
case 9:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 44 "setups.l"
{ cv_bool(yval(), &settings.si.restart); }
	YY_BREAK
case 10:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 45 "setups.l"
{ cv_bool(yval(), &settings.commentator); }
	YY_BREAK
case 11:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 46 "setups.l"
{ cv_bool(yval(), &settings.si.full_map); }
	YY_BREAK
case 12:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 47 "setups.l"
{ cv_bool(yval(), &settings.si.pay_to_play); }
	YY_BREAK
case 13:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 48 "setups.l"
{ cv_bool(yval(), &settings.robots_dont_win); }
	YY_BREAK
case 14:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 49 "setups.l"
{ cv_bool(yval(), &settings.max_armor_scale); }
	YY_BREAK
case 15:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 50 "setups.l"
{ cv_bool(yval(), &settings.si.no_nametags); }
	YY_BREAK
case 16:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 51 "setups.l"
{ cv_bool(yval(), &settings.si.no_radar); }
	YY_BREAK
case 17:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 52 "setups.l"
{ cv_bool(yval(), &settings.si.team_score); }
	YY_BREAK
case 18:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 53 "setups.l"
{ cv_bool(yval(), &settings.si.player_teleport); }
	YY_BREAK
case 19:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 54 "setups.l"
{ cv_bool(yval(), &settings.si.disc_teleport); }
	YY_BREAK
case 20:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 55 "setups.l"
{ cv_bool(yval(), &settings.si.teleport_from_team); }
	YY_BREAK
case 21:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 56 "setups.l"
{ cv_bool(yval(), &settings.si.teleport_from_neutral); }
	YY_BREAK
case 22:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 57 "setups.l"
{ cv_bool(yval(), &settings.si.teleport_to_team); }
	YY_BREAK
case 23:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 58 "setups.l"
{ cv_bool(yval(), &settings.si.teleport_to_neutral); }
	YY_BREAK
case 24:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 59 "setups.l"
{ cv_bool(yval(), &settings.si.teleport_any_to_any); }
	YY_BREAK
case 25:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 60 "setups.l"
{ cv_bool(yval(), &settings.si.war_goals_only); }
	YY_BREAK
case 26:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 61 "setups.l"
{ cv_bool(yval(), &settings.si.relative_disc); }
	YY_BREAK
case 27:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 62 "setups.l"
{ cv_bool(yval(), &settings.si.ultimate_own_goal); }
	YY_BREAK
case 28:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 63 "setups.l"
{ cv_int( yval(), &settings.si.winning_score); }
	YY_BREAK
case 29:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 64 "setups.l"
{ cv_int( yval(), &settings.si.outpost_strength); }
	YY_BREAK
case 30:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 65 "setups.l"
{ cv_flt( yval(), &settings.si.scroll_speed); }
	YY_BREAK
case 31:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 66 "setups.l"
{ cv_flt( yval(), &settings.si.box_slowdown); }
	YY_BREAK
case 32:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 67 "setups.l"
{ cv_flt( yval(), &settings.si.disc_friction); }
	YY_BREAK
case 33:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 68 "setups.l"
{ cv_flt( yval(), &settings.si.disc_speed); }
	YY_BREAK
case 34:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 69 "setups.l"
{ cv_flt( yval(), &settings.si.disc_damage); }
	YY_BREAK
case 35:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 70 "setups.l"
{ cv_flt( yval(), &settings.si.disc_heat); }
	YY_BREAK
case 36:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 71 "setups.l"
{ cv_flt( yval(), &settings.si.owner_slowdown); }
	YY_BREAK
case 37:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 72 "setups.l"
{ cv_flt( yval(), &settings.si.slip_friction); }
	YY_BREAK
case 38:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 73 "setups.l"
{ cv_flt( yval(), &settings.si.normal_friction); }
	YY_BREAK
case 39:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 74 "setups.l"
{ cv_int( yval(), &settings.si.shocker_walls); }
	YY_BREAK
case 40:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 75 "setups.l"
{ cv_int( yval(), &settings.difficulty); }
	YY_BREAK
case 41:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 77 "setups.l"
{
				/* we should load $2 if prog $1 doesn't exist */
				char *progname;
				char *progpath;
				int junk;
				
				strtoke(yytext, SEP);		/* "Program:	" */
				progname = strtoke(NULL, SEP);
				progpath = strtoke(NULL, SEP);

				if (DESC_LOADED != find_pdesc(progname, &junk)) {
					load_prog_desc(progpath, TRUE);
				}
}
	YY_BREAK
case 42:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 92 "setups.l"
{ /* Who cares... */ }
	YY_BREAK
case 43:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
# line 94 "setups.l"
{
			/* V#N: owner->name, disp, vptr->name, team, #progs, progs... */
				char buf[BUFLEN];
				char *cvn;
				char *cplayer;
				char *cdisp;
				char *cvname;
				char *cteam;
				char *cnprogs;
				char *cprog1;
				extern Combatant combatant[];
				extern char *teams_entries[];
				int vn, nprogs;
				int num;
				int i;

				cvn		=	2+strtoke(yytext, SEP);
				cplayer	=	strtoke(NULL, SEP);
				cdisp	=	strtoke(NULL, SEP);
				cvname	=	strtoke(NULL, SEP);
				cteam	=	strtoke(NULL, SEP);
				cnprogs	=	strtoke(NULL, SEP);
				cprog1	=	strtoke(NULL, SEP);
				
				/* printf("%s, %s, %s, %s, %s, %s, %s\n",
					cvn, cplayer, cdisp, cvname, cteam, cnprogs, cprog1); */
				
				vn = atoi(cvn);

				/* See get_player_info */

				combatant[vn].num_players = 1;
				strcpy(combatant[vn].name, cplayer);
				combatant[vn].player[0] = UNDEFINED;
				for(i = 0; i < num_terminals; i++) {
					if (strcmp(terminal[i]->player_name, cplayer)) continue;
					combatant[vn].player[0] = i;
				}

				if (DESC_LOADED == make_vdesc(cvname, &num)) {
					combatant[vn].vdesc = num;
				}
				else
				{
					fprintf(stderr, "Warning!  Cannot load vehicle %s\n",
							cvname);
				}

				nprogs = atoi(cnprogs);
				combatant[vn].program[0] = UNDEFINED;
				combatant[vn].num_programs = 0;
				if (nprogs && DESC_LOADED == find_pdesc(cprog1, &num)) {
					combatant[vn].num_programs = atoi(cnprogs);
					combatant[vn].program[0] = num;
				}

				/* printf("(%d: %s/%d)\n", combatant[vn].num_programs,
					cprog1, combatant[vn].program[0]); */

				cv_kw2i(cteam, &num, teams_entries, MAX_TEAMS);
				combatant[vn].team = num;

				combatant_to_grid(combatant + vn, atoi(cvn));
			}
	YY_BREAK
case 44:
# line 159 "setups.l"
{
				fprintf(stderr, "Bad setups file (%s)\n", yytext);
				exit(2);
			}
	YY_BREAK
case 45:
# line 164 "setups.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    register YY_CHAR *yy_bp = yytext;

    yy_current_state = yy_start;
    if ( yy_bp[-1] == '\n' )
	++yy_current_state;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 597 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 597 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 596);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
# line 164 "setups.l"


char *yval()
{
	char *cp;

	/* printf(":: %s\n", yytext); */

	for(cp = yytext; *cp != ':'; cp++) ;
	cp++;
	while(*cp == ' ' || *cp == '\t') cp++;

	return cp;
}

void cv_maze(val, maze)
char *val;
Mdesc **maze;
{
	int iCtr;
	extern int num_mdescs;
	extern Mdesc *mdesc;

	/* set to the random maze for now */
	*maze = (Mdesc *) NULL;

	/* need to search the mdesc[] to find the correct maze */
	for (iCtr = 0; iCtr < num_mdescs; iCtr++)
	{
		if (mdesc[iCtr].name)
		{
			if (! strcmp(mdesc[iCtr].name, val))
			{
				*maze = & mdesc[iCtr];
				break;
			}
		}
	}

	if (*maze == (Mdesc *) NULL)
	{
		fprintf(stderr, "Yo butthead!  Using the RANDOM maze.\n");
	}
}

void cv_str(val, store)
char *val;
char **store;
{
	*store = strdup(val);
}

void cv_kw2i(val, ival, arr, max)
char *val;
int *ival;
char *arr[];
int max;
{
	for(*ival = 0; *ival < max; *ival += 1) {
		if (!strcmp(arr[*ival], val)) return;
	}

	*ival = 0;
	return;
}

void cv_bool(val, bool)
char *val;
int *bool;
{
	*bool = (*val == '1');

	if (*val == '1' || *val == '0' && '\0' == *(val+1)) return;

	fprintf(stderr, "Bizare bool ('%c%c", *val, *(val+1));
	fprintf(stderr, "')!\n");
}

void cv_flt(val, fval)
char *val;
FLOAT *fval;
{
	*fval = atof(val);
}

void cv_int(val, ival)
char *val;
int *ival;
{
	*ival = atoi(val);
}

int load_settings(pcFileName)
	char *pcFileName;
{
	static int bCalled = FALSE;
	FILE *fp;

	fp = fopen(pcFileName, "r");
	if (!fp) {
		fprintf(stderr, "Can't find setups file\n");
		return (0);
	}

	if (bCalled)
	{
		yyrestart(fp);
		yylex();
	}
	else
	{
		yyin = fp;
		yylex();

		bCalled = TRUE;
	}

	fclose(fp);

	return(1);
}

/* Like ANSI strtok, but won't return an empty string */
char *strtoke(in, sep)
char *in, *sep;
{
	char *res;

	do {
		res = strtok(in, sep);
		in = NULL;
	} while(res && !*res);

	return res;
}
