/*
** Xtank
**
** This file is in the Public Domain.
**
** $Id$
*/

#ifdef SOUND

#ifndef	_sound_h
#define	_sound_h

#define NO_SOUND	"NONE"

typedef enum
{
	LMG_SOUND,
	MG_SOUND,
	HMG_SOUND,
	LCANNON_SOUND,
	CANNON_SOUND,
	HCANNON_SOUND,
	LROCKET_SOUND,
	ROCKET_SOUND,
	HROCKET_SOUND,
	ACID_SOUND,
	FLAME_SOUND,
	MINE_SOUND,
	SEEKER_SOUND,
	BLAST_SOUND,
	LASER_SOUND,
	SLICK_SOUND,
	PROCKET_SOUND,
	UMISSLE_SOUND,
	NUKE_SOUND,
	HARM_SOUND,
	DISC_SOUND,
	VEHICLE_HIT_WALL_SOUND,
	VEHICLE_HIT_VEHICLE_SOUND,
	TANK_EXPLOSION_SOUND,
	GLEAM_EXPLOSION_SOUND,
	DAM0_EXPLOSION_SOUND,
	DAM1_EXPLOSION_SOUND,
	DAM2_EXPLOSION_SOUND,
	DAM3_EXPLOSION_SOUND,
	DAM4_EXPLOSION_SOUND,
	EXHAUST_EXPLOSION_SOUND,
	ELECTRIC_EXPLOSION_SOUND,
	NUKE_EXPLOSION_SOUND,
	DAMAGE_EXPLOSION_SOUND,
	START_SOUND,
	END_SOUND,
	SONAR_SOUND,
	BLIP_SOUND,
	DISC_NEW_OWNER_SOUND,
	GOAL_SOUND,
	RICOCHET_SOUND,
	WEAPON_RELOADING_SOUND,
	WEAPON_NO_AMMO_SOUND,
	WEAPON_OFF_SOUND,
	WEAPON_TOO_HOT_SOUND,
	AMMO_WARNING_SOUND,
	ARMOR_WARNING_SOUND,
	HEAT_WARNING_SOUND,
	FUEL_WARNING_SOUND,
	AMMO_OK_SOUND,
	ARMOR_OK_SOUND,
	HEAT_OK_SOUND,
	FUEL_OK_SOUND,
	KILLER_SOUND,
	/*
	 * add new sounds above here
	 */
	MAX_SOUNDS
} SoundType;

#endif	_sound_h

#endif SOUND
